---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: openvswitch
namespace: openvswitch
readme: README.rst
repository: https://github.com/ansible-collections/openvswitch
